CREATE TABLE "usuario" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "fecha_nacimiento" date NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "saldo_idea" decimal(15,2) DEFAULT 0,
  "saldo_usdt" decimal(15,2) DEFAULT 0,
  "activo" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "rol" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "descripcion" varchar(300),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "permiso" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "descripcion" varchar(300),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "user_role" (
  "user_id" integer,
  "role_id" integer,
  PRIMARY KEY ("user_id", "role_id")
);

CREATE TABLE "role_permiso" (
  "permiso_id" integer,
  "role_id" integer,
  PRIMARY KEY ("permiso_id", "role_id")
);

CREATE TABLE "proyecto" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "titulo" varchar(200) NOT NULL,
  "descripcion" text,
  "monto_requerido" decimal(15,2) NOT NULL,
  "plazo" timestamp NOT NULL,
  "estado" varchar(50) NOT NULL,
  "gobernanza_comunidad" boolean DEFAULT false,
  "deleted_at" timestamp,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "subtoken" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "proyecto_id" integer UNIQUE NOT NULL,
  "nombre" varchar(20) NOT NULL,
  "suministro_total" integer NOT NULL,
  "cupo_restante" integer NOT NULL,
  "precio_actual" decimal(15,2) NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "portfolio_activo" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer NOT NULL,
  "subtoken_id" integer NOT NULL,
  "cantidad" integer NOT NULL DEFAULT 0,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "compra_saldo" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer NOT NULL,
  "monto_idea" decimal(15,2) NOT NULL,
  "monto_pagado_fiat" decimal(15,2) NOT NULL,
  "medio_pago" varchar(100) NOT NULL,
  "estado" varchar(50) DEFAULT 'completada',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "inversion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer NOT NULL,
  "proyecto_id" integer NOT NULL,
  "monto_idea" decimal(15,2) NOT NULL,
  "sub_tokens_recibidos" integer NOT NULL,
  "tx_hash" varchar(255),
  "estado" varchar(50) DEFAULT 'completada',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "movimiento_billetera" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer NOT NULL,
  "tipo_operacion" varchar(50) NOT NULL,
  "moneda" varchar(20) NOT NULL,
  "monto" decimal(15,2) NOT NULL,
  "tx_hash" varchar(255),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "transferencia_tokens" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "emisor_id" integer NOT NULL,
  "receptor_id" integer NOT NULL,
  "monto" decimal(15,2) NOT NULL,
  "tx_hash" varchar(255),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "transaccion_marketplace" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vendedor_id" integer NOT NULL,
  "comprador_id" integer NOT NULL,
  "subtoken_id" integer NOT NULL,
  "cantidad" integer NOT NULL,
  "precio_total" decimal(15,2) NOT NULL,
  "tx_hash" varchar(255),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "dividendos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "proyecto_id" integer NOT NULL,
  "usuario_id" integer NOT NULL,
  "monto_usdt" decimal(15,2) NOT NULL,
  "tx_hash" varchar(255),
  "fecha_distribucion" timestamp DEFAULT (now()),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "voto" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer NOT NULL,
  "proyecto_id" integer NOT NULL,
  "tokens_usados" integer NOT NULL,
  "tx_hash" varchar(255),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "evento" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(150) NOT NULL,
  "descripcion" text,
  "fecha_inicio" timestamp NOT NULL,
  "fecha_fin" timestamp NOT NULL,
  "recompensa_ofrecida" decimal(15,2),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "participacion_evento" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer NOT NULL,
  "evento_id" integer NOT NULL,
  "recompensa_recibida" decimal(15,2),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "nft_coleccionable" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer NOT NULL,
  "proyecto_id" integer NOT NULL,
  "metadatos_uri" varchar(255) NOT NULL,
  "tx_hash" varchar(255),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "notificacion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer NOT NULL,
  "titulo" varchar(150) NOT NULL,
  "mensaje" text NOT NULL,
  "leida" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now())
);

COMMENT ON COLUMN "usuario"."password_hash" IS 'HU01/HU02: Hash seguro';

COMMENT ON COLUMN "usuario"."saldo_idea" IS 'HU19: Saldo token utilitario';

COMMENT ON COLUMN "usuario"."saldo_usdt" IS 'HU19: Saldo moneda estable';

COMMENT ON COLUMN "usuario"."activo" IS 'HU04: Soft delete para desactivar usuario';

COMMENT ON COLUMN "proyecto"."descripcion" IS 'HU05: Descripción y objetivo';

COMMENT ON COLUMN "proyecto"."estado" IS 'HU08: preparacion, financiamiento, ejecucion, finalizado, cancelado';

COMMENT ON COLUMN "proyecto"."gobernanza_comunidad" IS 'HU32: Protocolo Takeover de gobernanza';

COMMENT ON COLUMN "subtoken"."suministro_total" IS 'HU09: Cantidad total definida';

COMMENT ON TABLE "portfolio_activo" IS 'Intermedia explícita N:M (HU35)';

COMMENT ON COLUMN "compra_saldo"."medio_pago" IS 'HU33: Pasarela de pago';

COMMENT ON COLUMN "inversion"."tx_hash" IS 'HU10/HU11: Trazabilidad blockchain';

COMMENT ON COLUMN "inversion"."estado" IS 'Puede pasar a "devuelta" (HU28)';

COMMENT ON COLUMN "movimiento_billetera"."tipo_operacion" IS 'Enum: carga, inversion, dividendo, transferencia, recompensa, devolucion (HU28), compensacion (HU31)';

COMMENT ON COLUMN "movimiento_billetera"."moneda" IS 'Enum: IDEA, USDT, SUBTOKEN';

COMMENT ON COLUMN "movimiento_billetera"."created_at" IS 'HU20: Historial de operaciones';

COMMENT ON COLUMN "transferencia_tokens"."monto" IS 'HU13: Transferencias P2P';

COMMENT ON COLUMN "transaccion_marketplace"."tx_hash" IS 'HU14: Marketplace';

COMMENT ON COLUMN "dividendos"."monto_usdt" IS 'HU16: Pago en USDT';

COMMENT ON COLUMN "dividendos"."created_at" IS 'HU17: Historial de dividendos';

COMMENT ON COLUMN "voto"."tokens_usados" IS 'HU21: Votación de proyecto';

COMMENT ON COLUMN "evento"."recompensa_ofrecida" IS 'HU23: Participación en evento';

COMMENT ON COLUMN "participacion_evento"."recompensa_recibida" IS 'HU22: Recompensas asignadas';

COMMENT ON COLUMN "nft_coleccionable"."metadatos_uri" IS 'HU24: Metadata única en blockchain';

COMMENT ON COLUMN "notificacion"."created_at" IS 'HU18: Sistema de notificacion';

ALTER TABLE "proyecto" ADD FOREIGN KEY ("user_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_role" ADD FOREIGN KEY ("user_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_role" ADD FOREIGN KEY ("role_id") REFERENCES "rol" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "role_permiso" ADD FOREIGN KEY ("permiso_id") REFERENCES "permiso" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "role_permiso" ADD FOREIGN KEY ("role_id") REFERENCES "rol" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "proyecto" ADD FOREIGN KEY ("id") REFERENCES "subtoken" ("proyecto_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "portfolio_activo" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "portfolio_activo" ADD FOREIGN KEY ("subtoken_id") REFERENCES "subtoken" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "compra_saldo" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inversion" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inversion" ADD FOREIGN KEY ("proyecto_id") REFERENCES "proyecto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "movimiento_billetera" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transferencia_tokens" ADD FOREIGN KEY ("emisor_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transferencia_tokens" ADD FOREIGN KEY ("receptor_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transaccion_marketplace" ADD FOREIGN KEY ("vendedor_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transaccion_marketplace" ADD FOREIGN KEY ("comprador_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transaccion_marketplace" ADD FOREIGN KEY ("subtoken_id") REFERENCES "subtoken" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "dividendos" ADD FOREIGN KEY ("proyecto_id") REFERENCES "proyecto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "dividendos" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "voto" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "voto" ADD FOREIGN KEY ("proyecto_id") REFERENCES "proyecto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "participacion_evento" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "participacion_evento" ADD FOREIGN KEY ("evento_id") REFERENCES "evento" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "nft_coleccionable" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "nft_coleccionable" ADD FOREIGN KEY ("proyecto_id") REFERENCES "proyecto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notificacion" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;
